services:
  app:
    image: analytics-api:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - PORT=8002
      - DATABASE_URL=NULL
    env_file:
      - .env
    ports:
      - "8080:8002" #systemPort:containerPort
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml