services:
  app:
    image: analytics-api:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env.compose
    ports:
      - "8080:8002" #systemPort:containerPort
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload 
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
  

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_USER=ts_user
      - POSTGRES_PASSWORD=ts_pass
      - POSTGRES_DB=timescaledb
    ports:
      - "8003:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ts_user -d stocks"]
      interval: 5s
      retries: 10
  
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: celery_worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    env_file:
      - .env.compose
    depends_on:
      - redis_service
      - timescaledb

  redis_service:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6379"


volumes:
  timescaledb_data: